### PR TITLE
Hacktoberfest: Add cron task for reboot "sticking" fans

### PR DESCRIPTION
**Pull request by saippuakauppias**

### CODE REVIEW

**Comment by saippuakauppias** [comment]
@andyljones Could you add "hacktoberfest" in topics to this repository?

```
Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.
```

https://hacktoberfest.digitalocean.com/

**Comment by andyljones** [comment]
Added the tag, but wrt the PR itself - unless I'm misunderstanding what the cronjob does, this seems like much more a job for whichever process is managing coolgpus. For systemd, I think the solution [would be](https://stackoverflow.com/questions/31055194/how-can-i-configure-a-systemd-service-to-restart-periodically): 

```
[Service]
Restart=always
RuntimeMaxSec=300
```

If you're using systemd, would you mind trying this out? If it works, we'll add this to the readme instead.

I'm also curious as to *why* your fans are sticking. This all fixes the symptoms rather than the disease. Is there any anomalous logging at times when it's stuck?

**Comment by saippuakauppias** [comment]
I probably won't be able to check the stickiness, because it happens about once a week and I don't want to leave the computer in a state where the video card may overheat :(

I will check your version with systemd and report the results. The main reason why I did the cron task was to close Xorgs beforehand.

What kind of logs are we talking about? Where can I see them? Maybe I can grep old records?

**Comment by andyljones** [comment]
The Xorgs should close automatically when the script is killed. 

You should be able to get the systemd logs with `journalctl -u coolgpus`. It should contain the last few months' worth of output; maybe you can find the events from before you started using the cronjob.

**Comment by andyljones** [comment]
Hrm - if the Xorgs are outliving the script, can you try upgrading to the latest version of coolgpus? It sounds like it might be related to [this issue](https://github.com/andyljones/coolgpus/issues/8).

**Comment by saippuakauppias** [comment]
It works for 3 days already as systemd without rebooting service and sticking.
¯ \ _ (ツ) _ / ¯

**Pull request closed without merging**
